

all : 
	cc -g -fsanitize=address -g3 push_swap.c ../utils/ft_lstadd_front.c ../utils/ft_lstnew.c ../instructions/instructions_2.c ../parsing/pars_push1.c ../utils/utils.c ../libft/ft_split.c ../libft/ft_atoi.c ../libft/ft_isdigit.c ../libft/ft_strlen.c ../utils/utils_2.c ../instructions/instructions_3.c ../instructions/instructions_1.c ../sort/sort_1.c ../sort/sort_2.c ../utils/utils_sort.c ../utils/utils_sort_2.c

r : 
	./a.out 54 -64 9169 73 9 5